services:
  mydb:
    image: mysql
    environment:
     MYSQL_DATABASE: wordpressdb
     MYSQL_ROOT_PASSWORD: Rahul@123
    ports:
     - 3306
   
  wp:
    image: wordpress 
    ports: 
     - 80:80
    environment:
     WORDPRESS_DB_HOST: db
     WORDPRESS_DB_USER: root
     WORDPRESS_DB_PASSWORD: Rahul@123
     WORDPRESS_DB_NAME: wordpressdb  
