services:
  mydb:
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_ROOT_PASSWORD: Rahul@123

  wordpress:
    image: wordpress
    ports:
      - 80:80
    depends_on: 
     - mydb 
    environment:
      WORDPRESS_DB_HOST: mydb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Rahul@123
      WORDPRESS_DB_NAME: wordpressdb
