services:
  database:
   image: mysql
   environment:
    MYSQL_ROOT_PASSWORD: Pass@123
    MYSQL_DATABASE: wordpressdb 
   ports:
     - 3306
   networks:
     - backend

  webtier:
   image: php:7.4-apache
   ports:
    - 80:80
   depends_on:
    - database
   networks:
     - frontend

  apptier:
   image: php:7.4-fpm
   depends_on:
    - database
   networks:
    - frontend
    - backend
 
networks:      
  frontend:
  backend:

