services:
  database:
   image: mysql
   environment:
    MYSQL_ROOT_PASSWORD: Pass@123
    MYSQL_DATABASE: wordpressdb
   ports:
    - 3306
  wordpress:
   image: wordpress
   ports:
    - 80:80
   depends_on:
     - database
   environment: 
    WORDPRESS_DB_HOST: database
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: Pass@123
    WORDPRESS_DB_NAME: wordpressdb

