services:
 database:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mysqlvol:/var/lib/mysql


 wordpress: 
  image: wordpress
  ports: 
  - 80:80
  depends_on:
  - database
  environment:
   WORDPRESS_DB_HOST: database
   WORDPRESS_DB_USER: root
   WORDPRESS_DB_PASSWORD: Pass@123
   WORDPRESS_DB_NAME: mydb
  volumes:
  - wpvol:/var/www/html/wp-content  

volumes:
  mysqlvol:
  wpvol:  



